# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby_crawl 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby_crawl"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["reiz"]
  s.date = "2014-05-25"
  s.description = "VersionEye crawlers implemented in Ruby"
  s.email = "robert.reiz.81@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "config/log4r.xml",
    "config/mongoid.yml",
    "config/settings.json",
    "lib/ruby_crawl.rb",
    "lib/versioneye/crawl.rb",
    "lib/versioneye/crawlers/bower_crawler.rb",
    "lib/versioneye/crawlers/cocoapods_crawler.rb",
    "lib/versioneye/crawlers/cocoapods_podspec_parser.rb",
    "lib/versioneye/crawlers/composer_utils.rb",
    "lib/versioneye/crawlers/crawler_utils.rb",
    "lib/versioneye/crawlers/git_crawler.rb",
    "lib/versioneye/crawlers/github_crawler.rb",
    "lib/versioneye/crawlers/github_version_crawler.rb",
    "lib/versioneye/crawlers/npm_crawler.rb",
    "lib/versioneye/crawlers/packagist_crawler.rb",
    "lib/versioneye/crawlers/tiki_crawler.rb",
    "log/logger.log",
    "ruby_crawl.gemspec",
    "test/helper.rb",
    "test/test_ruby_crawl.rb"
  ]
  s.homepage = "http://github.com/reiz/ruby_crawl"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "VersionEye crawlers implemented in Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<log4r>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<versioneye-core>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<log4r>, ["~> 1.1.0"])
      s.add_dependency(%q<versioneye-core>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<log4r>, ["~> 1.1.0"])
    s.add_dependency(%q<versioneye-core>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

